#! /usr/bin/env bash

set -euo pipefail

# Usage: ./build [--push] [--tag <tag>] [--flash-attention-2]

# Figure out if we should use python or python3
if command -v python3 &>/dev/null; then
  python_cmd=python3
else
  python_cmd=python
fi

version=$($python_cmd -c "from app.__version__ import version; print(version)")
echo "Building version $version"

# Parse arguments
push=false
tag="latest"
flash_attention_2=false
while [[ $# -gt 0 ]]; do
  case "$1" in
  --push)
    push=true
    shift
    ;;
  --tag)
    tag="$2"
    shift 2
    ;;
  --flash-attention-2)
    flash_attention_2=true
    shift
    ;;
  *)
    echo "Unknown argument: $1"
    exit 1
    ;;
  esac
done

base_tag="2.1.1-cuda12.1-cudnn8-runtime"
fa_arg="0"
if [ "$flash_attention_2" = true ]; then
  base_tag="2.1.1-cuda12.1-cudnn8-devel"
  tag="$tag-fa2"
  version="$version-fa2"
  fa_arg="1"
fi

docker buildx build \
  -t saladtechnologies/asr-api:$tag \
  --platform linux/amd64 \
  --output type=docker \
  --provenance false \
  -f Dockerfile \
  --build-arg BASE_TAG=$base_tag \
  --build-arg FLASH_ATTENTION_2=$fa_arg \
  .

docker tag saladtechnologies/asr-api:$tag saladtechnologies/asr-api:$version

if [ "$push" = true ]; then
  docker push saladtechnologies/asr-api:$tag
  docker push saladtechnologies/asr-api:$version
fi
