version: '3'

services:
  asr:
    image: saladtechnologies/asr-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    ports:
      - 8000:8000
    volumes:
      - ./data:/data
    environment:
      PORT: 8000
      CACHE_DIR: /data
      MODEL_ID: openai/whisper-large-v3
